---
deployment:
  tasks:
    - export DEPLOYPATH_public_html=/var/home/rasagaja/public_html/
    - export DEPLOYPATH_backend=/var/home/rasagaja/backend/

    - rm -rf $DEPLOYPATH_backend/src/
    - rm -f $DEPLOYPATH_backend/ReadMe.md
    - rm -f $DEPLOYPATH_backend/TODO.md
    - rm -f $DEPLOYPATH_backend/.htaccess

    - /bin/cp -R rasagaja/backend/* $DEPLOYPATH_backend
    - /bin/cp rasagaja/backend/.htaccess $DEPLOYPATH_backend

    - rm -rf $DEPLOYPATH_public_html/*
    - /bin/cp -R rasagaja/* $DEPLOYPATH_public_html

    - rm -rf $DEPLOYPATH_public_html/backend/src/
    - rm -f $DEPLOYPATH_public_html/backend/.gitignore
    - rm -f $DEPLOYPATH_public_html/backend/ReadMe.md
    - rm -f $DEPLOYPATH_public_html/backend/TODO.md
