---
deployment:
  tasks:
    - export DEPLOYPATH_public_html=/var/home/rasagaja/public_html/
    - export DEPLOYPATH_backend=/var/home/rasagaja/backend_pre/

    # - /bin/cp -R rasagaja/backend/* $DEPLOYPATH_backend
    # - /bin/cp rasagaja/backend/.htaccess $DEPLOYPATH_backend
    # - /bin/rm rasagaja/backend/.gitignore

    # - rm -rf $DEPLOYPATH_public_html/*
    # - /bin/cp -R rasagaja/* $DEPLOYPATH_public_html

    # - rm -rf $DEPLOYPATH_public_html/backend/src/
    # - rm -rf $DEPLOYPATH_public_html/backend/.gitignore
    # - rm -rf $DEPLOYPATH_public_html/backend/ReadMe.md
    # - rm -rf $DEPLOYPATH_public_html/backend/TODO.md
