---
deployment:
  tasks:
    - export DEPLOYPATH_public_html=/var/home/rasagaja/public_html/
    # - export DEPLOYPATH_backend=/var/home/rasagaja/backend/
    - rm -rf $DEPLOYPATH_public_html/*
    - /bin/cp -R rasagaja/* $DEPLOYPATH_public_html

    # - rm -rf $DEPLOYPATH_backend/*
    # - /bin/cp -R backend/* $DEPLOYPATH_backend
