---
deployment:
  tasks:
    # first make space to move the itmes

    - rm -r ~/public_html
    - rm -r ~/backend

    # second move the data

    - cp -r rasagaja/ ~/public_html
    - find ~/public_html/backend -mindepth 1 -maxdepth 1 ! -name '.htaccess' -exec rm -rf {} +