---
deployment:
  tasks:
    # first make space to move the itmes

    - rm -r ~/public_html
    - rm -r ~/backend

    # second move the data

    - cp -r rasagaja/ ~/public_html
    - cp -r rasagaja/backend ~/backend
    - find ~/public_html/backend -mindepth 1 -maxdepth 1 ! -name '.htaccess' -exec rm -rf {} +

    # Copy certificat

    - cp /etc/pki/tls/certs/ca-bundle.crt ~/backend/cacert.crt

    - touch ~/backend/tmp/restart.txt