# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/rasagaja/public_html/
#     - export MYPATH=rasagaja/
#     - /bin/cp -R $MYPATH/index.html $MYPATH/404.html $MYPATH/500.html $MYPATH/favicon.svg $MYPATH/robots.txt $MYPATH/LICENSE.txt $MYPATH/humans.txt $MYPATH/sitemap.xml $MYPATH/google7c41510533b69851.html $MYPATH/.htaccess $DEPLOYPATH
#     - /bin/cp -R $MYPATH/400 $MYPATH/403 $MYPATH/_astro $MYPATH/audio-irašai $MYPATH/fonts $MYPATH/401 $MYPATH/apie-save $MYPATH/audio-books $MYPATH/tekstai $DEPLOYPATH
    
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rasagaja/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH