---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rasagaja/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R rasagaja/index.html rasagaja/404.html rasagaja/500.html rasagaja/favicon.svg rasagaja/robots.txt rasagaja/humans.txt rasagaja/sitemap.xml $DEPLOYPATH
    - /bin/cp -R rasagaja/apie-save rasagaja/audio-books rasagaja/audio-irašai rasagaja/fonts rasagaja/tekstai rasagaja/_astro $DEPLOYPATH
    - /bin/cp -R rasagaja/.htaccess $DEPLOYPATH/.htaccess
    